INHERIT: images.yml
site_name: Test Site

theme: 
  name: material
  custom_dir: overrides

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true

nav:
  - 'index.md'
  - 'about.md'
  - 'gallery.md'